Working with pandas

In [1]:
import pandas as pd

In [2]:
dic={
    "StudentID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah", "Ian", "Julia"],
    "Age": [19, 20, 19, 21, 20, 22, 19, 20, 21, 19],
    "Major": ["Computer Science", "Mathematics", "Physics", "Biology", "Computer Science", 
              "Chemistry", "Mathematics", "Biology", "Physics", "Computer Science"],
    "GPA": [3.8, 3.2, 3.9, 3.5, 3.1, 4.0, 2.9, 3.7, 3.4, 3.9]
}

In [3]:
df=pd.DataFrame(dic)

In [5]:
df.head()

   StudentID     Name  Age             Major  GPA
0        101    Alice   19  Computer Science  3.8
1        102      Bob   20       Mathematics  3.2
2        103  Charlie   19           Physics  3.9
3        104    Diana   21           Biology  3.5
4        105    Ethan   20  Computer Science  3.1

In [6]:
df[df['Age']>20]

   StudentID   Name  Age      Major  GPA
3        104  Diana   21    Biology  3.5
5        106  Fiona   22  Chemistry  4.0
8        109    Ian   21    Physics  3.4

In [8]:
df.iloc[0:2,0:2]

   StudentID   Name
0        101  Alice
1        102    Bob

In [14]:
df.loc[0:3,'StudentID':'Age']

   StudentID     Name  Age
0        101    Alice   19
1        102      Bob   20
2        103  Charlie   19
3        104    Diana   21

In [21]:
df.isna().sum()

StudentID    0
Name         0
Age          0
Major        0
GPA          0
dtype: int64

In [22]:
df.fillna(0)

   StudentID     Name  Age             Major  GPA
0        101    Alice   19  Computer Science  3.8
1        102      Bob   20       Mathematics  3.2
2        103  Charlie   19           Physics  3.9
3        104    Diana   21           Biology  3.5
4        105    Ethan   20  Computer Science  3.1
5        106    Fiona   22         Chemistry  4.0
6        107   George   19       Mathematics  2.9
7        108   Hannah   20           Biology  3.7
8        109      Ian   21           Physics  3.4
9        110    Julia   19  Computer Science  3.9

In [26]:
df.isna().any()

StudentID    False
Name         False
Age          False
Major        False
GPA          False
dtype: bool

In [28]:
df.dropna(thresh=1)

   StudentID     Name  Age             Major  GPA
0        101    Alice   19  Computer Science  3.8
1        102      Bob   20       Mathematics  3.2
2        103  Charlie   19           Physics  3.9
3        104    Diana   21           Biology  3.5
4        105    Ethan   20  Computer Science  3.1
5        106    Fiona   22         Chemistry  4.0
6        107   George   19       Mathematics  2.9
7        108   Hannah   20           Biology  3.7
8        109      Ian   21           Physics  3.4
9        110    Julia   19  Computer Science  3.9

In [29]:
extra_data = {
    "StudentID": [101, 102, 103, 104, 105, 111, 112],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Seattle", "Miami"],
    "Club": ["Robotics", "Debate", "Chess", "Drama", "Robotics", "Band", "Chess"],
    "Has_Scholarship": [True, False, False, True, True, False, True]
}

df2=pd.DataFrame(extra_data)

In [33]:
df

   StudentID     Name  Age             Major  GPA
0        101    Alice   19  Computer Science  3.8
1        102      Bob   20       Mathematics  3.2
2        103  Charlie   19           Physics  3.9
3        104    Diana   21           Biology  3.5
4        105    Ethan   20  Computer Science  3.1
5        106    Fiona   22         Chemistry  4.0
6        107   George   19       Mathematics  2.9
7        108   Hannah   20           Biology  3.7
8        109      Ian   21           Physics  3.4
9        110    Julia   19  Computer Science  3.9

In [34]:
df2

   StudentID         City      Club  Has_Scholarship
0        101     New York  Robotics             True
1        102  Los Angeles    Debate            False
2        103      Chicago     Chess            False
3        104      Houston     Drama             True
4        105      Phoenix  Robotics             True
5        111      Seattle      Band            False
6        112        Miami     Chess             True

In [40]:
pd.merge(df,df2,on='StudentID',how='inner')

,StudentID,Name,Age,Major,GPA,City,Club,Has_Scholarship
0,101,Alice,19,Computer Science,3.8,New York,Robotics,True
1,102,Bob,20,Mathematics,3.2,Los Angeles,Debate,False
2,103,Charlie,19,Physics,3.9,Chicago,Chess,False
3,104,Diana,21,Biology,3.5,Houston,Drama,True
4,105,Ethan,20,Computer Science,3.1,Phoenix,Robotics,True

In [38]:
pd.concat([df,df2])

,StudentID,Name,Age,Major,GPA,City,Club,Has_Scholarship
0,101,Alice,19.0,Computer Science,3.8,NaN,NaN,NaN
1,102,Bob,20.0,Mathematics,3.2,NaN,NaN,NaN
2,103,Charlie,19.0,Physics,3.9,NaN,NaN,NaN
3,104,Diana,21.0,Biology,3.5,NaN,NaN,NaN
4,105,Ethan,20.0,Computer Science,3.1,NaN,NaN,NaN
5,106,Fiona,22.0,Chemistry,4.0,NaN,NaN,NaN
6,107,George,19.0,Mathematics,2.9,NaN,NaN,NaN
7,108,Hannah,20.0,Biology,3.7,NaN,NaN,NaN
8,109,Ian,21.0,Physics,3.4,NaN,NaN,NaN
9,110,Julia,19.0,Computer Science,3.9,NaN,NaN,NaN
0,101,NaN,NaN,NaN,NaN,New York,Robotics,True
1,102,NaN,NaN,NaN,NaN,Los Angeles,Debate,False
2,103,NaN,NaN,NaN,NaN,Chicago,Chess,False
3,104,NaN,NaN,NaN,NaN,Houston,Drama,True
4,105,NaN,NaN,NaN,NaN,Phoenix,Robotics,True
5,111,NaN,NaN,NaN,NaN,Seattle,Band,False
6,112,NaN,NaN,NaN,NaN,Miami,Chess,True

In [41]:
pd.concat([df,df2],axis=1)

,StudentID,Name,Age,Major,GPA,StudentID,City,Club,Has_Scholarship
0,101,Alice,19,Computer Science,3.8,101.0,New York,Robotics,True
1,102,Bob,20,Mathematics,3.2,102.0,Los Angeles,Debate,False
2,103,Charlie,19,Physics,3.9,103.0,Chicago,Chess,False
3,104,Diana,21,Biology,3.5,104.0,Houston,Drama,True
4,105,Ethan,20,Computer Science,3.1,105.0,Phoenix,Robotics,True
5,106,Fiona,22,Chemistry,4.0,111.0,Seattle,Band,False
6,107,George,19,Mathematics,2.9,112.0,Miami,Chess,True
7,108,Hannah,20,Biology,3.7,NaN,NaN,NaN,NaN
8,109,Ian,21,Physics,3.4,NaN,NaN,NaN,NaN
9,110,Julia,19,Computer Science,3.9,NaN,NaN,NaN,NaN

In [43]:
df.groupby('Age')['StudentID'].count()

Age
19    4
20    3
21    2
22    1
Name: StudentID, dtype: int64

In [44]:
df['GPA'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       35.400000
mean       3.540000
min        2.900000
max        4.000000
count     10.000000
std        0.380643
median     3.600000
Name: GPA, dtype: float64

In [48]:
pd.pivot_table(df,values='GPA',index='Major',columns='Name')

Name,Alice,Bob,Charlie,Diana,Ethan,Fiona,George,Hannah,Ian,Julia
Major,,,,,,,,,,
Biology,NaN,NaN,NaN,3.5,NaN,NaN,NaN,3.7,NaN,NaN
Chemistry,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
Computer Science,3.8,NaN,NaN,NaN,3.1,NaN,NaN,NaN,NaN,3.9
Mathematics,NaN,3.2,NaN,NaN,NaN,NaN,2.9,NaN,NaN,NaN
Physics,NaN,NaN,3.9,NaN,NaN,NaN,NaN,NaN,3.4,NaN